from typing import Any, Protocol

class SettingsPort(Protocol):
    def load_theme(self) -> str: ...
    def save_theme(self, theme: str) -> None: ...

    def load_language(self) -> str: ...
    def save_language(self, lang_code: str) -> None: ...

    def load_export_settings(self) -> dict[str, Any]: ...
    def get_export_default_dir(self) -> str: ...
    def save_export_default_dir(self, use_default_dir: bool, default_dir: str) -> None: ...
    def load_export_favorite_dir(self) -> str: ...
    def save_export_favorite_dir(self, favorite_dir: str) -> None: ...

    def load_ui_settings(self) -> dict[str, Any]: ...
    def save_ui_settings(self, config: dict[str, Any]) -> None: ...

    def load_main_window_geometry(self): ...
    def save_main_window_geometry(self, geometry) -> None: ...

    def load_anonymizer_presets(self) -> list[dict[str, Any]]: ...
    def save_anonymizer_presets(self, presets: list[dict[str, Any]]) -> None: ...

    def load_ai_settings(self) -> dict[str, Any]: ...
    def save_ai_settings(self, config: dict[str, Any]) -> None: ...
    def get_default_tokenizer_model(self) -> str: ...

    def load_ui_font_mode(self) -> str: ...
    def load_ui_font_family(self) -> str: ...
    def save_ui_font_settings(self, mode: str, family: str = "") -> None: ...

    def load_anonymization_settings(self) -> dict[str, Any]: ...
    def save_anonymization_settings(self, config: dict[str, Any]) -> None: ...
