"""
Theme palettes for Tkonverter application.
This file contains project-specific color palettes.
"""

from PyQt6.QtGui import QColor

LIGHT_THEME_PALETTE = {
    "Window": QColor("#ffffff"),
    "WindowText": QColor("#1f1f1f"),
    "Base": QColor("#ffffff"),
    "AlternateBase": QColor("#e1e1e1"),
    "ToolTipBase": QColor("#ffffff"),
    "ToolTipText": QColor("#1f1f1f"),
    "Text": QColor("#1f1f1f"),
    "Button": QColor("#e1e1e1"),
    "ButtonText": QColor("#1f1f1f"),
    "BrightText": QColor("#ff0000"),
    "Highlight": QColor("#0078D4"),
    "HighlightedText": QColor("#ffffff"),
    "accent": QColor("#0078D4"),
    "button.default.background": QColor("#ffffff"),
    "button.default.background.hover": QColor("#f8f8f8"),
    "button.default.background.pressed": QColor("#e9e9e9"),
    "button.default.border": QColor("#1E000000"),
    "button.default.bottom.edge": QColor("#32000000"),
    "button.delete.background": QColor("#26D93025"),
    "button.delete.background.hover": QColor("#4CD93025"),
    "button.delete.background.pressed": QColor("#4CD93025"),
    "button.delete.border": QColor("#66D93025"),
    "button.primary.background": QColor("#ffffff"),
    "button.primary.background.hover": QColor("#f8f8f8"),
    "button.primary.background.pressed": QColor("#e9e9e9"),
    "button.primary.border": QColor("#1E000000"),
    "button.primary.bottom.edge": QColor("#32000000"),
    "button.primary.text": QColor("#000000"),
    "input.border.thin": QColor("#2D000000"),
    "dialog.background": QColor("#ffffff"),
    "dialog.text": QColor("#1f1f1f"),
    "dialog.border": QColor("#c0c0c0"),
    "dialog.input.background": QColor("#ffffff"),
    "dialog.button.background": QColor("#e1e1e1"),
    "dialog.button.hover": QColor("#d8d8d8"),
    "dialog.button.ok.background": QColor("#0078D4"),
    "calendar.disabled.background": QColor("#fbe5e5"),
    "calendar.weekend.background": QColor("#f0f8ff"),
    "switch.track.off.border": QColor("#6E000000"),
    "switch.knob.off": QColor("#646464"),
    "switch.knob.on": QColor("#ffffff"),
    "switch.knob.border": QColor("#23000000"),
    "switch.text": QColor("#1f1f1f"),
    "help.nav.background": QColor("#f0f0f0"),
    "help.nav.border": QColor("#e0e0e0"),
    "help.nav.hover": QColor("#e8e8e8"),
    "help.nav.selected": QColor("#0078D4"),
    "help.nav.selected.text": QColor("#ffffff"),
    "flyout.background": QColor("#ffffff"),
    "flyout.border": QColor("#c0c0c0"),
    "list_item.background.hover": QColor("#f0f0f0"),
}

DARK_THEME_PALETTE = {
    "Window": QColor("#2b2b2b"),
    "WindowText": QColor("#ffffff"),
    "Base": QColor("#3c3c3c"),
    "AlternateBase": QColor("#313131"),
    "ToolTipBase": QColor("#3c3c3c"),
    "ToolTipText": QColor("#ffffff"),
    "Text": QColor("#ffffff"),
    "Button": QColor("#3c3c3c"),
    "ButtonText": QColor("#ffffff"),
    "BrightText": QColor("#ff0000"),
    "Highlight": QColor("#0096FF"),
    "HighlightedText": QColor("#ffffff"),
    "accent": QColor("#0096FF"),
    "button.default.background": QColor("#3c3c3c"),
    "button.default.background.hover": QColor("#4a4a4a"),
    "button.default.background.pressed": QColor("#555555"),
    "button.default.border": QColor("#26FFFFFF"),
    "button.default.bottom.edge": QColor("#1EFFFFFF"),
    "button.delete.background": QColor("#33D93025"),
    "button.delete.background.hover": QColor("#66D93025"),
    "button.delete.background.pressed": QColor("#66D93025"),
    "button.delete.border": QColor("#80D93025"),
    "button.primary.background": QColor("#3c3c3c"),
    "button.primary.background.hover": QColor("#4a4a4a"),
    "button.primary.background.pressed": QColor("#555555"),
    "button.primary.border": QColor("#26FFFFFF"),
    "button.primary.bottom.edge": QColor("#1EFFFFFF"),
    "button.primary.text": QColor("#dfdfdf"),
    "input.border.thin": QColor("#3CFFFFFF"),
    "dialog.background": QColor("#2b2b2b"),
    "dialog.text": QColor("#ffffff"),
    "dialog.border": QColor("#888888"),
    "dialog.input.background": QColor("#3c3c3c"),
    "dialog.button.background": QColor("#3c3c3c"),
    "dialog.button.hover": QColor("#4f4f4f"),
    "dialog.button.ok.background": QColor("#0096FF"),
    "calendar.disabled.background": QColor("#5a3e3e"),
    "calendar.weekend.background": QColor("#353535"),
    "switch.track.off.border": QColor("#78FFFFFF"),
    "switch.knob.off": QColor("#B4B4B4"),
    "switch.knob.on": QColor("#ffffff"),
    "switch.knob.border": QColor("#5A000000"),
    "switch.text": QColor("#ffffff"),
    "help.nav.background": QColor("#313131"),
    "help.nav.border": QColor("#444"),
    "help.nav.hover": QColor("#404040"),
    "help.nav.selected": QColor("#0096FF"),
    "help.nav.selected.text": QColor("#ffffff"),
    "flyout.background": QColor("#3c3c3c"),
    "flyout.border": QColor("#888888"),
    "list_item.background.hover": QColor("#404040"),
}

